### ISSUE TITLE
windows install

### ISSUE THREAD

**Issue by minemR** [atheriel/xrprof#25]
Hi,
as per:
**You can then launch "Rtools MinGW 64-bit" from the Start Menu and navigate to the source directory**
I can not find this under Start Menu. Can you please specify which .exe I need to use from Rtools?

**Comment by atheriel** [comment]
I'm not really sure what to do if your Rtools installation does not install these things correctly. You will have to investigate using their documentation (and the documentation for e.g. [msys2](https://www.msys2.org/) on which it is based).

**Comment by minemR** [comment]
Resolved. After installing newer version of Rtools (rtools40) the necessary .exe can be found under Start menu. The specific path is "\rtools40\mingw64.exe"
